apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce       # Only one node can mount this drive at a time
  resources:
    requests:
      storage: 1Gi        # We are asking for 1 GB of storage